### ISSUE TITLE
Create PATCH API Endpoint for Updating Message View Count

### ISSUE THREAD

**Issue by nesimtunc** [whispeer-me/backend#1]
**Problem:**
The current implementation increments the message view count upon fetching the message, leading to inaccurate counts due to failed decryption attempts being included.

**Proposed Solution:**
Implement a new PATCH API endpoint for specifically updating the `view_count` field of a message. This endpoint should only be called by the frontend after a message is successfully decrypted and viewed.

**Implementation Details:**
1. Develop a PATCH API endpoint (e.g., `/message/:id`) dedicated to updating the `view_count` field of the specified message.

**Acceptance Criteria:**
- A secure PATCH API endpoint for updating the `view_count` field is available.
- The `view_count` field is only updated through this endpoint and not during the message retrieval process.

**Comment by Arsaluddin** [comment]
assign this to me , i will try to do that

**Comment by nesimtunc** [comment]
You don't need assignment to do it, you could just fork it and send PR. However, I'm converting the apps into a full stack one, so, I will handle this issue. Thank you though.
